#!/bin/bash
# sys_info_page: программа вывода страницы с информацией о системе
PROGNAME=$(basename $0)
TITLE="System Information Report For $HOSTNAME"
CURRENT_TIME=$(date +"%x %r %Z")
TIME_STAMP="Generated $CURRENT_TIME, by $USER"

report_uptime () {
cat <<- _EOF_
<H2>System Uptime</H2>
<PRE>$(uptime)</PRE>
_EOF_
return
}

report_disk_space () {
cat <<- _EOF_
<H2>Disk Space Utilization</H2>
<PRE>$(df -h)</PRE>
_EOF_
return
}

report_home_space () {
local format="%8s%10s%10s\n"
local i dir_list total_files total_dirs total_size user_name
if [[ $(id -u) -eq 0 ]]; then
dir_list=/home/*
user_name="All Users"
else
dir_list=$HOME
user_name=$USER
fi
echo "<H2>Home Space Utilization ($user_name)</H2>"
for i in $dir_list; do
total_files=$(find $i -type f | wc -l)
total_dirs=$(find $i -type d | wc -l)
total_size=$(du -sh $i | cut -f 1)
echo "<H3>$i</H3>"
echo "<PRE>"
printf "$format" "Dirs" "Files" "Size"
printf "$format" "----" "-----" "----"
printf "$format" $total_dirs $total_files $total_size
echo "</PRE>"
done
return
}

write_html_page () {
cat <<- _EOF_
<HTML>
<HEAD>
<TITLE>$TITLE</TITLE>
</HEAD>
<BODY>
<H1>$TITLE</H1>
<P>$TIME_STAMP</P>
$CONTENT
</BODY>
</HTML>
_EOF_
return
}

# создание HTML-файла
filename="system_report.html"

# диалоговое окно для выбора функций
action=$(zenity --list --radiolist --title="System Information Report" \
--text="Выберите элементы из списка." \
--column="Выбор" --column="Действие" \
TRUE "Report uptime" \
FALSE "Report disk space" \
FALSE "Report home space" \
FALSE "View all the information" \
FALSE "EXIT")

case $action in
"Report uptime")
CONTENT=$(report_uptime)
write_html_page > $filename
zenity --info --text="HTML report generated successfully: $filename"
microsoft-edge $filename
firefox $filename
;;
"Report disk space")
CONTENT=$(report_disk_space)
write_html_page > $filename
zenity --info --text="HTML report generated successfully: $filename"
microsoft-edge $filename
firefox $filename
;;
"Report home space")
CONTENT=$(report_home_space)
write_html_page > $filename
zenity --info --text="HTML report generated successfully: $filename"
microsoft-edge $filename
firefox $filename
;;
"View all the information")
CONTENT="$(report_uptime)
$(report_disk_space)
$(report_home_space)"
write_html_page > $filename
zenity --info --text="HTML report generated successfully: $filename"
microsoft-edge $filename
firefox $filename
;;
"EXIT")
exit 0
;;
*)
zenity --error --text="Invalid selection."
exit 1
;;
esac
